// lib/mock-data/environmental.ts
// ============================================================
// EcoSphere – Environmental Module Mock Data
// ============================================================
import type { EmissionFactor, CarbonTransaction, EnvironmentalGoal } from '@/types';

// ── Emission Factors ─────────────────────────────────────────
export const emissionFactors: EmissionFactor[] = [
  { id: 'ef01', code: 'EF-2026-001', name: 'Grid Electricity – National Average', scope: 'scope2', activityType: 'electricity', factorValue: 0.8200, factorUnit: 'kgCO₂e/kWh',  activityUnit: 'kWh',  source: 'CEA India', year: 2026, category: 'Energy',    active: true  },
  { id: 'ef02', code: 'EF-2026-002', name: 'Diesel Combustion – Stationary',      scope: 'scope1', activityType: 'fuel',        factorValue: 2.6800, factorUnit: 'kgCO₂e/litre',activityUnit: 'litre',source: 'IPCC AR6',  year: 2026, category: 'Fuel',      active: true  },
  { id: 'ef03', code: 'EF-2026-003', name: 'Petrol – Mobile Combustion',          scope: 'scope1', activityType: 'fuel',        factorValue: 2.3100, factorUnit: 'kgCO₂e/litre',activityUnit: 'litre',source: 'IPCC AR6',  year: 2026, category: 'Fuel',      active: true  },
  { id: 'ef04', code: 'EF-2026-004', name: 'Domestic Air Travel',                 scope: 'scope3', activityType: 'travel_air',  factorValue: 0.2550, factorUnit: 'kgCO₂e/km',   activityUnit: 'km',   source: 'DEFRA 2026',year: 2026, category: 'Travel',    active: true  },
  { id: 'ef05', code: 'EF-2026-005', name: 'International Air Travel – Economy',  scope: 'scope3', activityType: 'travel_air',  factorValue: 0.1950, factorUnit: 'kgCO₂e/km',   activityUnit: 'km',   source: 'DEFRA 2026',year: 2026, category: 'Travel',    active: true  },
  { id: 'ef06', code: 'EF-2026-006', name: 'Road Travel – Personal Car',          scope: 'scope3', activityType: 'travel_road', factorValue: 0.1700, factorUnit: 'kgCO₂e/km',   activityUnit: 'km',   source: 'DEFRA 2026',year: 2026, category: 'Travel',    active: true  },
  { id: 'ef07', code: 'EF-2026-007', name: 'Rail Travel – Intercity',             scope: 'scope3', activityType: 'travel_rail', factorValue: 0.0410, factorUnit: 'kgCO₂e/km',   activityUnit: 'km',   source: 'DEFRA 2026',year: 2026, category: 'Travel',    active: true  },
  { id: 'ef08', code: 'EF-2026-008', name: 'Municipal Water Supply',              scope: 'scope3', activityType: 'water',       factorValue: 0.1440, factorUnit: 'kgCO₂e/m³',   activityUnit: 'm³',   source: 'GHG Protocol',year: 2025,category: 'Water',     active: true  },
  { id: 'ef09', code: 'EF-2026-009', name: 'Landfill Waste – Mixed',              scope: 'scope3', activityType: 'waste',       factorValue: 0.4670, factorUnit: 'kgCO₂e/tonne', activityUnit: 'tonne',source: 'IPCC AR6',  year: 2026, category: 'Waste',     active: true  },
  { id: 'ef10', code: 'EF-2026-010', name: 'R-410A Refrigerant Leakage',          scope: 'scope1', activityType: 'refrigerant', factorValue: 2088.0, factorUnit: 'kgCO₂e/kg',   activityUnit: 'kg',   source: 'IPCC AR6',  year: 2026, category: 'Refrigerant',active: true  },
  { id: 'ef11', code: 'EF-2026-011', name: 'Natural Gas – Stationary Combustion', scope: 'scope1', activityType: 'fuel',        factorValue: 1.9200, factorUnit: 'kgCO₂e/m³',   activityUnit: 'm³',   source: 'IPCC AR6',  year: 2026, category: 'Fuel',      active: true  },
  { id: 'ef12', code: 'EF-2026-012', name: 'Solar PV – Grid Displacement',        scope: 'scope2', activityType: 'electricity', factorValue: -0.8200,factorUnit: 'kgCO₂e/kWh',  activityUnit: 'kWh',  source: 'CEA India', year: 2026, category: 'Energy',    active: true  },
  { id: 'ef13', code: 'EF-2026-013', name: 'Grid Electricity (2025 baseline)',    scope: 'scope2', activityType: 'electricity', factorValue: 0.8560, factorUnit: 'kgCO₂e/kWh',  activityUnit: 'kWh',  source: 'CEA India', year: 2025, category: 'Energy',    active: false },
  { id: 'ef14', code: 'EF-2026-014', name: 'Paper – Office Consumption',          scope: 'scope3', activityType: 'material',    factorValue: 0.9200, factorUnit: 'kgCO₂e/kg',   activityUnit: 'kg',   source: 'DEFRA 2026',year: 2026, category: 'Material',  active: true  },
  { id: 'ef15', code: 'EF-2026-015', name: 'Diesel Generator',                    scope: 'scope1', activityType: 'fuel',        factorValue: 2.7200, factorUnit: 'kgCO₂e/litre',activityUnit: 'litre',source: 'IPCC AR6',  year: 2026, category: 'Fuel',      active: true  },
];

// ── Carbon Transactions ───────────────────────────────────────
export const carbonTransactions: CarbonTransaction[] = [
  { id: 'ct01', reference: 'CT-2026-001', date: '2026-07-01', department: 'Engineering',     departmentId: 'd1', category: 'Energy',    emissionFactor: 'Grid Electricity',          emissionFactorId: 'ef01', quantity: 12400, unit: 'kWh',   co2Equivalent:  10.17, scope: 'scope2', state: 'confirmed' },
  { id: 'ct02', reference: 'CT-2026-002', date: '2026-07-02', department: 'Operations',       departmentId: 'd3', category: 'Fuel',      emissionFactor: 'Diesel Combustion',         emissionFactorId: 'ef02', quantity:   480, unit: 'litre', co2Equivalent:   1.29, scope: 'scope1', state: 'confirmed' },
  { id: 'ct03', reference: 'CT-2026-003', date: '2026-07-03', department: 'Finance',         departmentId: 'd4', category: 'Travel',    emissionFactor: 'Domestic Air Travel',        emissionFactorId: 'ef04', quantity:  3200, unit: 'km',    co2Equivalent:   0.82, scope: 'scope3', state: 'confirmed' },
  { id: 'ct04', reference: 'CT-2026-004', date: '2026-07-05', department: 'Engineering',     departmentId: 'd1', category: 'Energy',    emissionFactor: 'Grid Electricity',          emissionFactorId: 'ef01', quantity:  8200, unit: 'kWh',   co2Equivalent:   6.72, scope: 'scope2', state: 'confirmed' },
  { id: 'ct05', reference: 'CT-2026-005', date: '2026-07-06', department: 'Human Resources', departmentId: 'd2', category: 'Travel',    emissionFactor: 'Road Travel – Personal Car', emissionFactorId: 'ef06', quantity:  1500, unit: 'km',    co2Equivalent:   0.26, scope: 'scope3', state: 'confirmed' },
  { id: 'ct06', reference: 'CT-2026-006', date: '2026-07-08', department: 'Operations',       departmentId: 'd3', category: 'Waste',     emissionFactor: 'Landfill Waste – Mixed',    emissionFactorId: 'ef09', quantity:    12, unit: 'tonne', co2Equivalent:   5.60, scope: 'scope3', state: 'confirmed' },
  { id: 'ct07', reference: 'CT-2026-007', date: '2026-07-10', department: 'Marketing',        departmentId: 'd5', category: 'Travel',    emissionFactor: 'International Air Travel',   emissionFactorId: 'ef05', quantity:  8400, unit: 'km',    co2Equivalent:   1.64, scope: 'scope3', state: 'confirmed' },
  { id: 'ct08', reference: 'CT-2026-008', date: '2026-07-12', department: 'Engineering',     departmentId: 'd1', category: 'Energy',    emissionFactor: 'Solar PV',                  emissionFactorId: 'ef12', quantity:  5000, unit: 'kWh',   co2Equivalent:  -4.10, scope: 'scope2', state: 'confirmed', notes: 'Solar panel output offset' },
  { id: 'ct09', reference: 'CT-2026-009', date: '2026-07-14', department: 'Finance',         departmentId: 'd4', category: 'Energy',    emissionFactor: 'Grid Electricity',          emissionFactorId: 'ef01', quantity:  3800, unit: 'kWh',   co2Equivalent:   3.12, scope: 'scope2', state: 'confirmed' },
  { id: 'ct10', reference: 'CT-2026-010', date: '2026-07-15', department: 'Operations',       departmentId: 'd3', category: 'Fuel',      emissionFactor: 'Petrol – Mobile',           emissionFactorId: 'ef03', quantity:   320, unit: 'litre', co2Equivalent:   0.74, scope: 'scope1', state: 'confirmed' },
  { id: 'ct11', reference: 'CT-2026-011', date: '2026-07-16', department: 'Engineering',     departmentId: 'd1', category: 'Refrigerant',emissionFactor: 'R-410A Refrigerant',       emissionFactorId: 'ef10', quantity:     2, unit: 'kg',    co2Equivalent:   4.18, scope: 'scope1', state: 'confirmed' },
  { id: 'ct12', reference: 'CT-2026-012', date: '2026-07-17', department: 'Human Resources', departmentId: 'd2', category: 'Material',  emissionFactor: 'Paper – Office',            emissionFactorId: 'ef14', quantity:    45, unit: 'kg',    co2Equivalent:   0.04, scope: 'scope3', state: 'confirmed' },
  { id: 'ct13', reference: 'CT-2026-013', date: '2026-07-18', department: 'Operations',       departmentId: 'd3', category: 'Energy',    emissionFactor: 'Diesel Generator',          emissionFactorId: 'ef15', quantity:   180, unit: 'litre', co2Equivalent:   0.49, scope: 'scope1', state: 'confirmed' },
  { id: 'ct14', reference: 'CT-2026-014', date: '2026-07-19', department: 'Marketing',        departmentId: 'd5', category: 'Water',     emissionFactor: 'Municipal Water Supply',     emissionFactorId: 'ef08', quantity:   240, unit: 'm³',    co2Equivalent:   0.35, scope: 'scope3', state: 'confirmed' },
  { id: 'ct15', reference: 'CT-2026-015', date: '2026-07-20', department: 'Finance',         departmentId: 'd4', category: 'Travel',    emissionFactor: 'Rail Travel',               emissionFactorId: 'ef07', quantity:  4200, unit: 'km',    co2Equivalent:   0.17, scope: 'scope3', state: 'confirmed' },
  { id: 'ct16', reference: 'CT-2026-016', date: '2026-07-22', department: 'Engineering',     departmentId: 'd1', category: 'Energy',    emissionFactor: 'Grid Electricity',          emissionFactorId: 'ef01', quantity:  9600, unit: 'kWh',   co2Equivalent:   7.87, scope: 'scope2', state: 'draft'     },
  { id: 'ct17', reference: 'CT-2026-017', date: '2026-07-23', department: 'Operations',       departmentId: 'd3', category: 'Fuel',      emissionFactor: 'Diesel Combustion',         emissionFactorId: 'ef02', quantity:   210, unit: 'litre', co2Equivalent:   0.56, scope: 'scope1', state: 'draft'     },
  { id: 'ct18', reference: 'CT-2026-018', date: '2026-07-24', department: 'Human Resources', departmentId: 'd2', category: 'Waste',     emissionFactor: 'Landfill Waste – Mixed',    emissionFactorId: 'ef09', quantity:     4, unit: 'tonne', co2Equivalent:   1.87, scope: 'scope3', state: 'draft'     },
  { id: 'ct19', reference: 'CT-2026-019', date: '2026-07-01', department: 'Marketing',        departmentId: 'd5', category: 'Energy',    emissionFactor: 'Grid Electricity',          emissionFactorId: 'ef01', quantity:  2200, unit: 'kWh',   co2Equivalent:   1.80, scope: 'scope2', state: 'cancelled', notes: 'Duplicate entry – cancelled' },
  { id: 'ct20', reference: 'CT-2026-020', date: '2026-07-25', department: 'Engineering',     departmentId: 'd1', category: 'Fuel',      emissionFactor: 'Natural Gas',               emissionFactorId: 'ef11', quantity:   380, unit: 'm³',    co2Equivalent:   0.73, scope: 'scope1', state: 'draft'     },
];

// ── Environmental Goals ───────────────────────────────────────
export const environmentalGoals: EnvironmentalGoal[] = [
  { id: 'eg01', reference: 'EG-2026-001', name: 'Reduce Total Carbon Footprint',         department: 'All Departments',  departmentId: 'all', category: 'Carbon',      targetValue: 1500, currentValue: 1284, unit: 'tCO₂e',    progress: 85.6, startDate: '2026-01-01', deadline: '2026-12-31', daysRemaining: 172, responsiblePerson: 'Kiran Patel',    state: 'active',   isOverdue: false, priority: '2' },
  { id: 'eg02', reference: 'EG-2026-002', name: 'Switch to 100% Renewable Energy',       department: 'Engineering',      departmentId: 'd1', category: 'Energy',      targetValue: 100,  currentValue: 42,   unit: '% renewable',progress: 42.0, startDate: '2026-01-01', deadline: '2026-12-31', daysRemaining: 172, responsiblePerson: 'Rahul Mehta',    state: 'active',   isOverdue: false, priority: '2' },
  { id: 'eg03', reference: 'EG-2026-003', name: 'Reduce AC Electricity Consumption',     department: 'Engineering',      departmentId: 'd1', category: 'Energy',      targetValue: 15,   currentValue: 18.2, unit: '% reduction', progress: 100,  startDate: '2026-01-01', deadline: '2026-06-30', daysRemaining: 0,   responsiblePerson: 'Suresh Iyer',    state: 'achieved', isOverdue: false, priority: '1' },
  { id: 'eg04', reference: 'EG-2026-004', name: 'Zero Plastic in Office Cafeteria',       department: 'Operations',       departmentId: 'd3', category: 'Waste',       targetValue: 100,  currentValue: 78,   unit: '% plastic-free',progress: 78,  startDate: '2026-03-01', deadline: '2026-09-30', daysRemaining: 80,  responsiblePerson: 'Kiran Patel',    state: 'active',   isOverdue: false, priority: '1' },
  { id: 'eg05', reference: 'EG-2026-005', name: 'Reduce Business Travel Emissions',       department: 'Finance',          departmentId: 'd4', category: 'Travel',      targetValue: 30,   currentValue: 22.1, unit: '% reduction', progress: 73.7, startDate: '2026-01-01', deadline: '2026-06-30', daysRemaining: 0,   responsiblePerson: 'Sunita Joshi',   state: 'missed',   isOverdue: true,  priority: '1' },
  { id: 'eg06', reference: 'EG-2026-006', name: 'Install Rainwater Harvesting System',    department: 'Operations',       departmentId: 'd3', category: 'Water',       targetValue: 1,    currentValue: 1,    unit: 'system',      progress: 100,  startDate: '2026-01-01', deadline: '2026-05-31', daysRemaining: 0,   responsiblePerson: 'Kiran Patel',    state: 'achieved', isOverdue: false, priority: '0' },
  { id: 'eg07', reference: 'EG-2026-007', name: 'Paper-Free Policy Compliance',           department: 'Human Resources',  departmentId: 'd2', category: 'Material',    targetValue: 95,   currentValue: 88,   unit: '% digital',   progress: 92.6, startDate: '2026-04-01', deadline: '2026-12-31', daysRemaining: 172, responsiblePerson: 'Anita Sharma',   state: 'active',   isOverdue: false, priority: '0' },
  { id: 'eg08', reference: 'EG-2026-008', name: 'Plant 500 Trees – Green Campus',         department: 'All Departments',  departmentId: 'all', category: 'Biodiversity',targetValue: 500,  currentValue: 500,  unit: 'trees',       progress: 100,  startDate: '2026-01-01', deadline: '2026-06-30', daysRemaining: 0,   responsiblePerson: 'Anita Sharma',   state: 'achieved', isOverdue: false, priority: '1' },
  { id: 'eg09', reference: 'EG-2026-009', name: 'Reduce Diesel Generator Usage',          department: 'Operations',       departmentId: 'd3', category: 'Fuel',        targetValue: 50,   currentValue: 18,   unit: '% reduction', progress: 36.0, startDate: '2026-04-01', deadline: '2026-07-15', daysRemaining: 0,   responsiblePerson: 'Kiran Patel',    state: 'missed',   isOverdue: true,  priority: '2' },
  { id: 'eg10', reference: 'EG-2026-010', name: 'Green Commute Program (50% adoption)',   department: 'Human Resources',  departmentId: 'd2', category: 'Travel',      targetValue: 50,   currentValue: 34,   unit: '% employees', progress: 68.0, startDate: '2026-05-01', deadline: '2026-10-31', daysRemaining: 111, responsiblePerson: 'Anita Sharma',   state: 'active',   isOverdue: false, priority: '1' },
  { id: 'eg11', reference: 'EG-2026-011', name: 'ISO 14001 Certification',                department: 'All Departments',  departmentId: 'all', category: 'Compliance',  targetValue: 1,    currentValue: 0,    unit: 'certification',progress: 0,   startDate: '2026-07-01', deadline: '2026-12-31', daysRemaining: 172, responsiblePerson: 'Rahul Mehta',    state: 'draft',    isOverdue: false, priority: '2' },
  { id: 'eg12', reference: 'EG-2026-012', name: 'Carbon Neutral Canteen Operations',      department: 'Operations',       departmentId: 'd3', category: 'Carbon',      targetValue: 0,    currentValue: 12,   unit: 'tCO₂e',       progress: 60.0, startDate: '2026-01-01', deadline: '2026-08-31', daysRemaining: 50,  responsiblePerson: 'Kiran Patel',    state: 'active',   isOverdue: false, priority: '1' },
];
